# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UrbanSpatialPatternAnalysis_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UrbanSpatialPatternAnalysisDialogBase(object):
    def setupUi(self, UrbanSpatialPatternAnalysisDialogBase):
        UrbanSpatialPatternAnalysisDialogBase.setObjectName("UrbanSpatialPatternAnalysisDialogBase")
        UrbanSpatialPatternAnalysisDialogBase.resize(738, 733)
        self.button_box = QtWidgets.QDialogButtonBox(UrbanSpatialPatternAnalysisDialogBase)
        self.button_box.setGeometry(QtCore.QRect(210, 630, 201, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(UrbanSpatialPatternAnalysisDialogBase)
        self.label.setGeometry(QtCore.QRect(40, 20, 221, 16))
        self.label.setObjectName("label")
        self.indicatorComboBox = QtWidgets.QComboBox(UrbanSpatialPatternAnalysisDialogBase)
        self.indicatorComboBox.setGeometry(QtCore.QRect(270, 20, 361, 22))
        self.indicatorComboBox.setObjectName("indicatorComboBox")
        self.label_6 = QtWidgets.QLabel(UrbanSpatialPatternAnalysisDialogBase)
        self.label_6.setGeometry(QtCore.QRect(40, 510, 181, 16))
        self.label_6.setObjectName("label_6")
        self.outputFileWidget = QgsFileWidget(UrbanSpatialPatternAnalysisDialogBase)
        self.outputFileWidget.setGeometry(QtCore.QRect(230, 500, 381, 27))
        self.outputFileWidget.setObjectName("outputFileWidget")
        self.buildRasterGroup = QtWidgets.QGroupBox(UrbanSpatialPatternAnalysisDialogBase)
        self.buildRasterGroup.setGeometry(QtCore.QRect(50, 90, 591, 91))
        self.buildRasterGroup.setObjectName("buildRasterGroup")
        self.label_2 = QtWidgets.QLabel(self.buildRasterGroup)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 291, 16))
        self.label_2.setObjectName("label_2")
        self.buildRasterFileWidget = QgsFileWidget(self.buildRasterGroup)
        self.buildRasterFileWidget.setGeometry(QtCore.QRect(310, 40, 181, 27))
        self.buildRasterFileWidget.setObjectName("buildRasterFileWidget")
        self.vectorGroup = QtWidgets.QGroupBox(UrbanSpatialPatternAnalysisDialogBase)
        self.vectorGroup.setGeometry(QtCore.QRect(50, 330, 591, 131))
        self.vectorGroup.setObjectName("vectorGroup")
        self.label_4 = QtWidgets.QLabel(self.vectorGroup)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 341, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.vectorGroup)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 351, 16))
        self.label_5.setObjectName("label_5")
        self.roadNetworkFileWidget = QgsFileWidget(self.vectorGroup)
        self.roadNetworkFileWidget.setGeometry(QtCore.QRect(390, 30, 181, 27))
        self.roadNetworkFileWidget.setObjectName("roadNetworkFileWidget")
        self.analysisAreaFileWidget = QgsFileWidget(self.vectorGroup)
        self.analysisAreaFileWidget.setGeometry(QtCore.QRect(390, 80, 181, 27))
        self.analysisAreaFileWidget.setObjectName("analysisAreaFileWidget")
        self.heightRasterGroup = QtWidgets.QGroupBox(UrbanSpatialPatternAnalysisDialogBase)
        self.heightRasterGroup.setGeometry(QtCore.QRect(50, 210, 591, 91))
        self.heightRasterGroup.setObjectName("heightRasterGroup")
        self.label_3 = QtWidgets.QLabel(self.heightRasterGroup)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 271, 16))
        self.label_3.setObjectName("label_3")
        self.heightRasterFileWidget = QgsFileWidget(self.heightRasterGroup)
        self.heightRasterFileWidget.setGeometry(QtCore.QRect(260, 40, 171, 27))
        self.heightRasterFileWidget.setObjectName("heightRasterFileWidget")
        self.csvOutputCheckBox = QtWidgets.QCheckBox(UrbanSpatialPatternAnalysisDialogBase)
        self.csvOutputCheckBox.setGeometry(QtCore.QRect(140, 550, 511, 19))
        self.csvOutputCheckBox.setChecked(True)
        self.csvOutputCheckBox.setObjectName("csvOutputCheckBox")
        self.pngOutputCheckBox = QtWidgets.QCheckBox(UrbanSpatialPatternAnalysisDialogBase)
        self.pngOutputCheckBox.setGeometry(QtCore.QRect(140, 590, 561, 19))
        self.pngOutputCheckBox.setChecked(True)
        self.pngOutputCheckBox.setObjectName("pngOutputCheckBox")

        self.retranslateUi(UrbanSpatialPatternAnalysisDialogBase)
        self.button_box.accepted.connect(UrbanSpatialPatternAnalysisDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(UrbanSpatialPatternAnalysisDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UrbanSpatialPatternAnalysisDialogBase)

    def retranslateUi(self, UrbanSpatialPatternAnalysisDialogBase):
        _translate = QtCore.QCoreApplication.translate
        UrbanSpatialPatternAnalysisDialogBase.setWindowTitle(_translate("UrbanSpatialPatternAnalysisDialogBase", "UrbanSpatialPatternAnalysis"))
        self.label.setText(_translate("UrbanSpatialPatternAnalysisDialogBase", "Select Analysis Metrics:"))
        self.label_6.setText(_translate("UrbanSpatialPatternAnalysisDialogBase", "Output result path:"))
        self.buildRasterGroup.setTitle(_translate("UrbanSpatialPatternAnalysisDialogBase", "Building Classification Grid Input"))
        self.label_2.setText(_translate("UrbanSpatialPatternAnalysisDialogBase", "Architectural Grid (build.tif):"))
        self.vectorGroup.setTitle(_translate("UrbanSpatialPatternAnalysisDialogBase", "Vector Data Input"))
        self.label_4.setText(_translate("UrbanSpatialPatternAnalysisDialogBase", "Road Network (roadNetworkFileWidget) "))
        self.label_5.setText(_translate("UrbanSpatialPatternAnalysisDialogBase", "Analysis Area (analysisAreaFileWidget)"))
        self.heightRasterGroup.setTitle(_translate("UrbanSpatialPatternAnalysisDialogBase", "Building Height Grid Input"))
        self.label_3.setText(_translate("UrbanSpatialPatternAnalysisDialogBase", "Height Grid (height.tif):"))
        self.csvOutputCheckBox.setText(_translate("UrbanSpatialPatternAnalysisDialogBase", "Simultaneously output detailed data in a .csv file"))
        self.pngOutputCheckBox.setText(_translate("UrbanSpatialPatternAnalysisDialogBase", "Simultaneously output the statistical chart .png file"))
from qgsfilewidget import QgsFileWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UrbanSpatialPatternAnalysisDialogBase = QtWidgets.QDialog()
    ui = Ui_UrbanSpatialPatternAnalysisDialogBase()
    ui.setupUi(UrbanSpatialPatternAnalysisDialogBase)
    UrbanSpatialPatternAnalysisDialogBase.show()
    sys.exit(app.exec_())
